#obj-$(CONFIG_QCI_FINPOINT):= qci_finpoint.o
#obj-m:= qci_finpoint.o
#new i2c style driver 
#qci_finpoint-objs := src_new/qci_finpoint_new.o
#obj-m := src_new/qci_finpoint_new.o

ccflags-y += -Iarch/arm/mach-tegra/nvrm/core/common
ccflags-y += -Iarch/arm/mach-tegra/nvrm/core

obj-y		+= qci_finpoint.o
